import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from 'react-i18next';
import Button from '@/ui/atoms/Button';
import Card from '@/ui/atoms/Card';
import Input from '@/ui/atoms/Input';
import Select from '@/ui/atoms/Select';
import Textarea from '@/ui/atoms/Textarea';
export default function InvoiceForm({ form, errors, saving, patients, loadingPatients, patientsError, submitError, onRetryPatients, onChange, onSubmit, }) {
    const { t } = useTranslation('invoices');
    return (_jsx(Card, { title: t('form.title'), description: t('form.description'), children: patientsError ? (_jsxs("div", { className: "rounded-2xl border border-danger/20 bg-danger/10 px-4 py-3 text-sm text-danger", children: [_jsx("div", { children: patientsError }), _jsx(Button, { size: "sm", variant: "outline", className: "mt-3", onClick: onRetryPatients, children: t('actions.retry') })] })) : (_jsxs("form", { className: "grid gap-3 md:grid-cols-2", onSubmit: onSubmit, children: [_jsxs(Select, { label: t('fields.patient'), name: "patientId", value: form.patientId, error: errors.patientId, disabled: saving || loadingPatients, onChange: (event) => onChange('patientId', event.target.value), children: [_jsx("option", { value: "", children: loadingPatients ? t('labels.loadingPatients') : t('form.selectPatient') }), patients.map((patient) => (_jsx("option", { value: patient.value, children: patient.label }, patient.value)))] }), _jsx(Input, { label: t('fields.amount'), name: "amount", type: "number", min: "0", step: "0.01", value: form.amount, error: errors.amount, onChange: (event) => onChange('amount', event.target.value) }), _jsx(Input, { label: t('fields.date'), name: "invoiceDate", type: "date", value: form.invoiceDate, error: errors.invoiceDate, onChange: (event) => onChange('invoiceDate', event.target.value) }), _jsx("div", { className: "hidden md:block" }), _jsx("div", { className: "md:col-span-2", children: _jsx(Textarea, { label: t('fields.description'), name: "description", value: form.description, error: errors.description, onChange: (event) => onChange('description', event.target.value) }) }), submitError ? (_jsx("div", { className: "md:col-span-2 rounded-2xl border border-danger/20 bg-danger/10 px-4 py-3 text-sm text-danger", children: submitError })) : null, _jsx("div", { className: "md:col-span-2", children: _jsx(Button, { type: "submit", loading: saving, children: t('form.submit') }) })] })) }));
}
