/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#edf9fb',
          100: '#d4f0f4',
          200: '#addfe8',
          300: '#7ac8d8',
          400: '#4faec3',
          500: '#2f8eab',
          600: '#256f8d',
          700: '#205b73',
          800: '#1f4d5f',
          900: '#1f4352',
          950: '#122b3a',
        },
        background: 'hsl(var(--background) / <alpha-value>)',
        foreground: 'hsl(var(--foreground) / <alpha-value>)',
        surface: 'hsl(var(--surface) / <alpha-value>)',
        card: 'hsl(var(--card) / <alpha-value>)',
        border: 'hsl(var(--border) / <alpha-value>)',
        muted: 'hsl(var(--muted) / <alpha-value>)',
        'muted-foreground': 'hsl(var(--muted-foreground) / <alpha-value>)',
        primary: 'hsl(var(--primary) / <alpha-value>)',
        'primary-foreground': 'hsl(var(--primary-foreground) / <alpha-value>)',
        secondary: 'hsl(var(--secondary) / <alpha-value>)',
        'secondary-foreground': 'hsl(var(--secondary-foreground) / <alpha-value>)',
        accent: 'hsl(var(--accent) / <alpha-value>)',
        'accent-foreground': 'hsl(var(--accent-foreground) / <alpha-value>)',
        success: 'hsl(var(--success) / <alpha-value>)',
        warning: 'hsl(var(--warning) / <alpha-value>)',
        attention: 'hsl(var(--attention) / <alpha-value>)',
        danger: 'hsl(var(--danger) / <alpha-value>)',
        ring: 'hsl(var(--ring) / <alpha-value>)',
        tx: {
          light: '#0f172a',
          dark: '#e2e8f0',
          primary: '#1f4d5f',
          secondary: '#5f7482',
        },
        bg: {
          light: '#ffffff',
          dark: '#0b1420',
          darkSecondary: '#101a2a',
          grayPrimary: '#f1f5f9',
          graySecondary: '#f8fafc',
          grayDark: '#e2e8f0',
          primary: '#1f4d5f',
        },
        bd: {
          light: '#cbd5e1',
          dark: '#2f445d',
          default: '#d7dee6',
          graySecondary: '#8ca0b0',
          darkDefault: '#93a7bc',
        },
      },
      boxShadow: {
        soft: '0 8px 24px -12px rgba(18, 43, 58, 0.35)',
        panel: '0 20px 50px -22px rgba(16, 40, 58, 0.4)',
      },
      fontFamily: {
        sans: ['Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
