export function lt(en, de) {
    return { en, de };
}
export function pickText(language, value) {
    return value[language] ?? value.en;
}
export const commonCopy = {
    appName: lt('MedSphere', 'MedSphere'),
    appSubtitle: lt('Connected care operations for modern clinics and hospitals.', 'Vernetzte Pflegeabläufe für moderne Kliniken und Krankenhäuser.'),
    loginTitle: lt('Welcome back', 'Willkommen zurück'),
    loginDescription: lt('Sign in to manage patients, staff, rooms, and appointments across MedSphere.', 'Melden Sie sich an, um Patienten, Personal, Zimmer und Termine in MedSphere zu verwalten.'),
    loadingSession: lt('Restoring your session...', 'Ihre Sitzung wird wiederhergestellt...'),
    create: lt('Create', 'Erstellen'),
    edit: lt('Edit', 'Bearbeiten'),
    delete: lt('Delete', 'Löschen'),
    cancel: lt('Cancel', 'Abbrechen'),
    close: lt('Close', 'Schließen'),
    save: lt('Save', 'Speichern'),
    update: lt('Update', 'Aktualisieren'),
    filters: lt('Filters', 'Filter'),
    clear: lt('Clear', 'Zurücksetzen'),
    retry: lt('Retry', 'Erneut versuchen'),
    actions: lt('Actions', 'Aktionen'),
    results: lt('Results', 'Ergebnisse'),
    sortBy: lt('Sort by', 'Sortieren nach'),
    order: lt('Order', 'Reihenfolge'),
    ascending: lt('Ascending', 'Aufsteigend'),
    descending: lt('Descending', 'Absteigend'),
    rowsPerPage: lt('Rows per page', 'Zeilen pro Seite'),
    previous: lt('Previous', 'Zurück'),
    next: lt('Next', 'Weiter'),
    emptyTitle: lt('No data yet', 'Noch keine Daten'),
    emptyDescription: lt('Try changing the filters or create a new record.', 'Versuchen Sie, die Filter anzupassen oder einen neuen Eintrag zu erstellen.'),
    errorTitle: lt('Something went wrong', 'Etwas ist schiefgelaufen'),
    networkError: lt('We could not reach the server. Check your connection and try again.', 'Der Server konnte nicht erreicht werden. Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.'),
    timeoutError: lt('The request took too long. Please try again.', 'Die Anfrage hat zu lange gedauert. Bitte versuchen Sie es erneut.'),
    validationError: lt('Please review the information and try again.', 'Bitte überprüfen Sie die Angaben und versuchen Sie es erneut.'),
    notFoundError: lt('We could not find the requested data.', 'Die angeforderten Daten konnten nicht gefunden werden.'),
    conflictError: lt('This item could not be saved right now. Please refresh and try again.', 'Dieses Element kann momentan nicht gespeichert werden. Aktualisieren Sie die Seite und versuchen Sie es erneut.'),
    serverError: lt('The server is having trouble right now. Please try again in a moment.', 'Der Server hat derzeit Probleme. Bitte versuchen Sie es in einem Moment erneut.'),
    genericError: lt('We could not complete your request. Please try again.', 'Ihre Anfrage konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.'),
    unauthorizedTitle: lt('Session expired', 'Sitzung abgelaufen'),
    unauthorizedDescription: lt('Please sign in again to continue.', 'Bitte melden Sie sich erneut an, um fortzufahren.'),
    forbiddenTitle: lt('Access denied', 'Zugriff verweigert'),
    forbiddenDescription: lt('Your role cannot access this resource.', 'Ihre Rolle hat keinen Zugriff auf diese Ressource.'),
    loginRateLimitError: lt('Too many login attempts, please try again in 15 minutes', 'Zu viele Anmeldeversuche. Bitte versuchen Sie es in 15 Minuten erneut.'),
    loginSuccess: lt('Signed in successfully.', 'Anmeldung erfolgreich.'),
    createSuccess: lt('Created successfully.', 'Erfolgreich erstellt.'),
    updateSuccess: lt('Updated successfully.', 'Erfolgreich aktualisiert.'),
    deleteSuccess: lt('Deleted successfully.', 'Erfolgreich gelöscht.'),
    deleteTitle: lt('Delete record', 'Eintrag löschen'),
    deleteDescription: lt('This action cannot be undone.', 'Diese Aktion kann nicht rückgängig gemacht werden.'),
    confirmDelete: lt('Delete', 'Löschen'),
    theme: lt('Theme', 'Design'),
    light: lt('Light', 'Hell'),
    dark: lt('Dark', 'Dunkel'),
    language: lt('Language', 'Sprache'),
    dashboard: lt('Dashboard', 'Dashboard'),
    todayAppointments: lt("Today's appointments", 'Heutige Termine'),
    availableRooms: lt('Available rooms', 'Verfügbare Zimmer'),
    activeAdmissions: lt('Active admissions', 'Aktive Aufnahmen'),
    totalRecords: lt('Total records', 'Gesamteinträge'),
    noItems: lt('Nothing to show.', 'Nichts anzuzeigen.'),
    search: lt('Search', 'Suchen'),
    identifier: lt('Email or username', 'E-Mail oder Benutzername'),
    password: lt('Password', 'Passwort'),
    signIn: lt('Sign in', 'Anmelden'),
    signOut: lt('Sign out', 'Abmelden'),
    signOutAll: lt('Sign out all devices', 'Von allen Geräten abmelden'),
    notAvailable: lt('Not available', 'Nicht verfügbar'),
    mobileMenu: lt('Open menu', 'Menü öffnen'),
    pageSummary: lt('Page', 'Seite'),
    createRecord: lt('Create record', 'Eintrag erstellen'),
    editRecord: lt('Edit record', 'Eintrag bearbeiten'),
    createNew: lt('Create new', 'Neu erstellen'),
    passwordMinLength: lt('Use at least 6 characters.', 'Verwenden Sie mindestens 6 Zeichen.'),
    passwordMaxLength: lt('Use 255 characters or fewer.', 'Verwenden Sie höchstens 255 Zeichen.'),
    passwordMismatch: lt('Passwords do not match.', 'Die Passwörter stimmen nicht überein.'),
    changePassword: lt('Change password', 'Passwort ändern'),
    resetPassword: lt('Reset password', 'Passwort zurücksetzen'),
    currentPassword: lt('Current password', 'Aktuelles Passwort'),
    newPassword: lt('New password', 'Neues Passwort'),
    confirmPassword: lt('Confirm password', 'Passwort bestätigen'),
    passwordUpdated: lt('Password updated. Please sign in again.', 'Passwort aktualisiert. Bitte melden Sie sich erneut an.'),
    passwordResetSuccess: lt('Password reset successfully.', 'Passwort erfolgreich zurückgesetzt.'),
    passwordChangeDescription: lt('Update your password to keep your account secure.', 'Aktualisieren Sie Ihr Passwort, um Ihr Konto sicher zu halten.'),
    passwordResetDescription: lt('Set a temporary password for this linked user account.', 'Legen Sie ein temporäres Passwort für dieses verknüpfte Benutzerkonto fest.'),
};
