export function lt(en, sq) {
    return { en, sq };
}
export function pickText(language, value) {
    return value[language] ?? value.en;
}
export const commonCopy = {
    appName: lt('Hospital Management System', 'Sistemi i Menaxhimit të Spitalit'),
    appSubtitle: lt('Simple frontend connected to your backend.', 'Frontend i thjeshtë i lidhur me backend-in tuaj.'),
    loginTitle: lt('Welcome back', 'Mirë se u ktheve'),
    loginDescription: lt('Sign in to manage patients, staff, rooms, and appointments.', 'Hyni për të menaxhuar pacientët, stafin, dhomat dhe terminet.'),
    loadingSession: lt('Restoring your session...', 'Po rikthejmë sesionin tuaj...'),
    create: lt('Create', 'Krijo'),
    edit: lt('Edit', 'Ndrysho'),
    delete: lt('Delete', 'Fshi'),
    cancel: lt('Cancel', 'Anulo'),
    close: lt('Close', 'Mbyll'),
    save: lt('Save', 'Ruaj'),
    update: lt('Update', 'Përditëso'),
    filters: lt('Filters', 'Filtrat'),
    clear: lt('Clear', 'Pastro'),
    retry: lt('Retry', 'Provo sërish'),
    actions: lt('Actions', 'Veprimet'),
    results: lt('Results', 'Rezultatet'),
    sortBy: lt('Sort by', 'Rendit sipas'),
    order: lt('Order', 'Renditja'),
    ascending: lt('Ascending', 'Në rritje'),
    descending: lt('Descending', 'Në zbritje'),
    rowsPerPage: lt('Rows per page', 'Rreshta për faqe'),
    previous: lt('Previous', 'Më parë'),
    next: lt('Next', 'Tjetër'),
    emptyTitle: lt('No data yet', 'Nuk ka të dhëna ende'),
    emptyDescription: lt('Try changing the filters or create a new record.', 'Provoni të ndryshoni filtrat ose krijoni një rekord të ri.'),
    errorTitle: lt('Something went wrong', 'Diçka shkoi keq'),
    networkError: lt('We could not reach the server. Check your connection and try again.', 'Nuk mundëm të lidhemi me serverin. Kontrolloni lidhjen dhe provoni sërish.'),
    timeoutError: lt('The request took too long. Please try again.', 'Kërkesa zgjati shumë. Ju lutem provoni sërish.'),
    validationError: lt('Please review the information and try again.', 'Ju lutem kontrolloni të dhënat dhe provoni sërish.'),
    notFoundError: lt('We could not find the requested data.', 'Nuk i gjetëm të dhënat e kërkuara.'),
    conflictError: lt('This item could not be saved right now. Please refresh and try again.', 'Ky element nuk mund të ruhet tani. Rifreskoni faqen dhe provoni sërish.'),
    serverError: lt('The server is having trouble right now. Please try again in a moment.', 'Serveri po has vështirësi tani. Ju lutem provoni përsëri pas pak.'),
    genericError: lt('We could not complete your request. Please try again.', 'Nuk mundëm ta përfundojmë kërkesën tuaj. Ju lutem provoni sërish.'),
    unauthorizedTitle: lt('Session expired', 'Sesioni ka skaduar'),
    unauthorizedDescription: lt('Please sign in again to continue.', 'Ju lutem hyni përsëri për të vazhduar.'),
    forbiddenTitle: lt('Access denied', 'Qasja u refuzua'),
    forbiddenDescription: lt('Your role cannot access this resource.', 'Roli juaj nuk ka qasje në këtë burim.'),
    loginRateLimitError: lt('Too many login attempts, please try again in 15 minutes', 'Shumë tentativa hyrjeje. Ju lutem provoni sërish pas 15 minutash.'),
    loginSuccess: lt('Signed in successfully.', 'Hyrja u krye me sukses.'),
    createSuccess: lt('Created successfully.', 'U krijua me sukses.'),
    updateSuccess: lt('Updated successfully.', 'U përditësua me sukses.'),
    deleteSuccess: lt('Deleted successfully.', 'U fshi me sukses.'),
    deleteTitle: lt('Delete record', 'Fshi rekordin'),
    deleteDescription: lt('This action cannot be undone.', 'Ky veprim nuk mund të kthehet prapa.'),
    confirmDelete: lt('Delete', 'Fshi'),
    theme: lt('Theme', 'Tema'),
    light: lt('Light', 'E çelët'),
    dark: lt('Dark', 'E errët'),
    language: lt('Language', 'Gjuha'),
    dashboard: lt('Dashboard', 'Paneli'),
    todayAppointments: lt("Today's appointments", 'Terminet e sotme'),
    availableRooms: lt('Available rooms', 'Dhomat e lira'),
    activeAdmissions: lt('Active admissions', 'Pranimet aktive'),
    totalRecords: lt('Total records', 'Totali i rekordeve'),
    noItems: lt('Nothing to show.', 'Nuk ka çfarë të shfaqet.'),
    search: lt('Search', 'Kërko'),
    identifier: lt('Email or username', 'Email ose emër përdoruesi'),
    password: lt('Password', 'Fjalëkalimi'),
    signIn: lt('Sign in', 'Hyr'),
    signOut: lt('Sign out', 'Dil'),
    signOutAll: lt('Sign out all devices', 'Dil nga të gjitha pajisjet'),
    notAvailable: lt('Not available', 'Nuk është në dispozicion'),
    mobileMenu: lt('Open menu', 'Hap menunë'),
    pageSummary: lt('Page', 'Faqja'),
    createRecord: lt('Create record', 'Krijo rekord'),
    editRecord: lt('Edit record', 'Ndrysho rekordin'),
    createNew: lt('Create new', 'Krijo të ri'),
};
