import { jsx as _jsx } from "react/jsx-runtime";
import { StrictMode } from 'react';
import ReactDOM from 'react-dom/client';
import '@/index.css';
import '@/config/i18n';
import { applyTheme, getInitialTheme } from '@/config/theme';
import AppProviders from '@/hms/providers/AppProviders';
import App from './App';
applyTheme(getInitialTheme());
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(StrictMode, { children: _jsx(AppProviders, { children: _jsx(App, {}) }) }));
